language: python
matrix:
  include:
    - os: linux
      sudo: required
      python: 3.6
      env: TOXENV=py36
    - os: osx
      language: generic
      sudo: required
      env: TOXENV=py36
install:
  ./.travis/install.sh
script: pyinstaller --windowed --onefile converter.py