language: python
matrix:
  include:
  - os: linux
    sudo: required
    python: 3.6
    env: TOXENV=py36
  - os: osx
    language: generic
    sudo: required
    env: TOXENV=py36
before_install:
- chmod +x '.travis/install.sh'
install: "./.travis/install.sh"
script: pyinstaller --console --windowed --onefile converter.py
deploy:
  provider: releases
  api_key:
    secure: 2eS1vtTY/T+kmIlLPoTVmndXY+jCoxeIk5SD9sEPkYil9/CKKBSqGSVGA7Q++IUbDwXDEfRMqlXNoZ/nWPZEmSLQT0gJXoB2XeK4jOqzbu9lnToCBDl5OmgwYejmEg7RYq/m/+560c3cKxfXbPKog2xLCkUw5rPzoYT9+xHm3QgJrtVeY/LrpGg/1cfRBBQmLk4b2HXUcojmgvoIXqe3yZEBwMUvXOH8FMDO6TXlutg5Q5NJm4DbTzAB82EjZsVNnuYudDLE6PowZ9ftgQyWHDOJSAIUHRjHNgzHLQ5BA6iuNEYLwx3uhRZ/Zvtwzc67AkuhsjlEmK05dRFZyZOtednKzb7WmTUySbsVvEWlJXOUe+XBbSh7x6bSoBf3xHxQQPDj9JNXC/N30GEEsFA29GjnpakR8zm9AQRJrASljckkYx2BpJxsmAwrMAf1W4ahLBSy8ps+IQqhqIRzo8hUlRemEDzxsILycWC7Egxg0RhYVVjnyTUd5rAOU4ZB/iDpiDWnxMQ2CCYXVbh1EizPVkNACYWP9PB9bXWrpsGcddM4k6tcdxAv99KEpLSijP3G5KHRhwqCQb4f6x0Dy59rfk127a+No8GEBgkdpdd/jgdyHKGXS/ihc4PAjy5U8vx6IiUw6k01jqanOxjblTsVIrA5QaEtoQISUeanw1M5bhc=
  file: dist/converter
