# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Development\youtubeconverter\pydownload.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 594)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.fileTable = QtWidgets.QTableWidget(self.centralwidget)
        self.fileTable.setObjectName("fileTable")
        self.fileTable.setColumnCount(0)
        self.fileTable.setRowCount(0)
        self.gridLayout.addWidget(self.fileTable, 0, 0, 10, 1)
        self.console = QtWidgets.QTextBrowser(self.centralwidget)
        self.console.setObjectName("console")
        self.gridLayout.addWidget(self.console, 0, 1, 1, 4)
        self.enterURL = QtWidgets.QLabel(self.centralwidget)
        self.enterURL.setObjectName("enterURL")
        self.gridLayout.addWidget(self.enterURL, 1, 1, 1, 1)
        self.urlBox = QtWidgets.QLineEdit(self.centralwidget)
        self.urlBox.setObjectName("urlBox")
        self.gridLayout.addWidget(self.urlBox, 2, 1, 1, 4)
        self.type = QtWidgets.QLabel(self.centralwidget)
        self.type.setObjectName("type")
        self.gridLayout.addWidget(self.type, 3, 2, 1, 2)
        self.fileType = QtWidgets.QComboBox(self.centralwidget)
        self.fileType.setObjectName("fileType")
        self.fileType.addItem("")
        self.fileType.addItem("")
        self.gridLayout.addWidget(self.fileType, 3, 4, 1, 1)
        self.chooseDirectory = QtWidgets.QLabel(self.centralwidget)
        self.chooseDirectory.setObjectName("chooseDirectory")
        self.gridLayout.addWidget(self.chooseDirectory, 4, 1, 1, 1)
        self.processURL = QtWidgets.QPushButton(self.centralwidget)
        self.processURL.setObjectName("processURL")
        self.gridLayout.addWidget(self.processURL, 4, 4, 1, 1)
        self.dlDirectory = QtWidgets.QLineEdit(self.centralwidget)
        self.dlDirectory.setObjectName("dlDirectory")
        self.gridLayout.addWidget(self.dlDirectory, 5, 1, 1, 3)
        self.browseDir = QtWidgets.QPushButton(self.centralwidget)
        self.browseDir.setObjectName("browseDir")
        self.gridLayout.addWidget(self.browseDir, 5, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 1, 1, 1)
        self.filename = QtWidgets.QLineEdit(self.centralwidget)
        self.filename.setObjectName("filename")
        self.gridLayout.addWidget(self.filename, 7, 1, 1, 4)
        self.fileFormat = QtWidgets.QComboBox(self.centralwidget)
        self.fileFormat.setObjectName("fileFormat")
        self.fileFormat.addItem("")
        self.gridLayout.addWidget(self.fileFormat, 8, 4, 1, 1)
        self.download = QtWidgets.QPushButton(self.centralwidget)
        self.download.setObjectName("download")
        self.gridLayout.addWidget(self.download, 9, 3, 1, 2)
        self.format = QtWidgets.QLabel(self.centralwidget)
        self.format.setObjectName("format")
        self.gridLayout.addWidget(self.format, 8, 1, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.download.clicked.connect(self.urlBox.clear)
        self.urlBox.returnPressed.connect(self.processURL.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.urlBox, self.fileType)
        MainWindow.setTabOrder(self.fileType, self.fileFormat)
        MainWindow.setTabOrder(self.fileFormat, self.processURL)
        MainWindow.setTabOrder(self.processURL, self.browseDir)
        MainWindow.setTabOrder(self.browseDir, self.dlDirectory)
        MainWindow.setTabOrder(self.dlDirectory, self.download)
        MainWindow.setTabOrder(self.download, self.fileTable)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python Youtube Downloader"))
        self.enterURL.setText(_translate("MainWindow", "Enter URL"))
        self.type.setText(_translate("MainWindow", "Choose Type"))
        self.fileType.setItemText(0, _translate("MainWindow", "Video"))
        self.fileType.setItemText(1, _translate("MainWindow", "Audio"))
        self.chooseDirectory.setText(_translate("MainWindow", "Choose Directory"))
        self.processURL.setText(_translate("MainWindow", "Process URL"))
        self.browseDir.setText(_translate("MainWindow", "Browse"))
        self.label.setText(_translate("MainWindow", "Type Filename (or leave blank for default)"))
        self.fileFormat.setItemText(0, _translate("MainWindow", "x264"))
        self.download.setText(_translate("MainWindow", "Download"))
        self.format.setText(_translate("MainWindow", "Choose Video Encoder (when using video type only)"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))

