# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Development\youtubeconverter\pydownload.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.urlBox = QtWidgets.QLineEdit(self.centralwidget)
        self.urlBox.setGeometry(QtCore.QRect(360, 270, 421, 21))
        self.urlBox.setObjectName("urlBox")
        self.download = QtWidgets.QPushButton(self.centralwidget)
        self.download.setGeometry(QtCore.QRect(664, 512, 101, 31))
        self.download.setObjectName("download")
        self.processURL = QtWidgets.QPushButton(self.centralwidget)
        self.processURL.setGeometry(QtCore.QRect(700, 330, 75, 23))
        self.processURL.setObjectName("processURL")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(360, 512, 291, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.fileTable = QtWidgets.QTableWidget(self.centralwidget)
        self.fileTable.setGeometry(QtCore.QRect(10, 10, 331, 521))
        self.fileTable.setObjectName("fileTable")
        self.fileTable.setColumnCount(0)
        self.fileTable.setRowCount(0)
        self.fileType = QtWidgets.QComboBox(self.centralwidget)
        self.fileType.setGeometry(QtCore.QRect(704, 300, 69, 22))
        self.fileType.setObjectName("fileType")
        self.fileType.addItem("")
        self.fileType.addItem("")
        self.type = QtWidgets.QLabel(self.centralwidget)
        self.type.setGeometry(QtCore.QRect(610, 300, 81, 20))
        self.type.setObjectName("type")
        self.format = QtWidgets.QLabel(self.centralwidget)
        self.format.setGeometry(QtCore.QRect(600, 460, 91, 20))
        self.format.setObjectName("format")
        self.fileFormat = QtWidgets.QComboBox(self.centralwidget)
        self.fileFormat.setGeometry(QtCore.QRect(710, 460, 69, 22))
        self.fileFormat.setObjectName("fileFormat")
        self.dlDirectory = QtWidgets.QLineEdit(self.centralwidget)
        self.dlDirectory.setGeometry(QtCore.QRect(360, 370, 341, 21))
        self.dlDirectory.setObjectName("dlDirectory")
        self.chooseDirectory = QtWidgets.QLabel(self.centralwidget)
        self.chooseDirectory.setGeometry(QtCore.QRect(360, 350, 101, 16))
        self.chooseDirectory.setObjectName("chooseDirectory")
        self.browseDir = QtWidgets.QPushButton(self.centralwidget)
        self.browseDir.setGeometry(QtCore.QRect(710, 370, 75, 23))
        self.browseDir.setObjectName("browseDir")
        self.enterURL = QtWidgets.QLabel(self.centralwidget)
        self.enterURL.setGeometry(QtCore.QRect(360, 250, 47, 13))
        self.enterURL.setObjectName("enterURL")
        self.console = QtWidgets.QTextBrowser(self.centralwidget)
        self.console.setGeometry(QtCore.QRect(360, 10, 421, 231))
        self.console.setObjectName("console")
        self.filename = QtWidgets.QLineEdit(self.centralwidget)
        self.filename.setGeometry(QtCore.QRect(360, 430, 421, 20))
        self.filename.setObjectName("filename")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 410, 211, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.download.clicked.connect(self.urlBox.clear)
        self.urlBox.returnPressed.connect(self.processURL.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.urlBox, self.fileType)
        MainWindow.setTabOrder(self.fileType, self.fileFormat)
        MainWindow.setTabOrder(self.fileFormat, self.processURL)
        MainWindow.setTabOrder(self.processURL, self.browseDir)
        MainWindow.setTabOrder(self.browseDir, self.dlDirectory)
        MainWindow.setTabOrder(self.dlDirectory, self.download)
        MainWindow.setTabOrder(self.download, self.fileTable)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python Youtube Downloader"))
        self.download.setText(_translate("MainWindow", "Download"))
        self.processURL.setText(_translate("MainWindow", "Process URL"))
        self.fileType.setItemText(0, _translate("MainWindow", "Video"))
        self.fileType.setItemText(1, _translate("MainWindow", "Audio"))
        self.type.setText(_translate("MainWindow", "Choose Type"))
        self.format.setText(_translate("MainWindow", "Choose Format"))
        self.chooseDirectory.setText(_translate("MainWindow", "Choose Directory"))
        self.browseDir.setText(_translate("MainWindow", "Browse"))
        self.enterURL.setText(_translate("MainWindow", "Enter URL"))
        self.label.setText(_translate("MainWindow", "Type Filename (or leave blank for default)"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))

